### ISSUE TITLE
Format error in train.txt

### ISSUE THREAD

**Issue by suned** [zhangdongxu/kbp37#3]
I found the following on line 20205 in `train.txt`:
```
5051	"<e1> NUGW </e1> National Council is in turn affiliated to National Trade Union Council ( PMme2> #jf/e2> ? Zenrokyo ) the smallest of the three national labour federations in Japan .."
```
Probably its a formatting error.

**Comment by suned** [comment]
Similarly, for relation 14918 in `train.txt`:
```
14918	"ASIN : B0000DJWDG Performed by <e1> Mikuni Shimokawa </e1> collected on the single album L / ?e2> ? </e2> published by Pony Canyon .."
```

**Comment by zhangdongxu** [comment]
This error was caused by removing those non-utf8 characters previously. 
I have pushed a new version, where I also removed some question marks like "??", "??????". About 0.3% of entities will become empty. But this should not significantly influence the experiment performance. 

Thanks again~ cheers!

**Comment by suned** [comment]
Beautiful. Thanks :)
